name: Deployment Exercise 2
on: [push,workflow_dispatch]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: npm ci
      - name: Test Code
        run: npm run test          
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build
        
    #   - name: Configure Git for gh-pages
    #     run: |
    #       git config --global user.name "github-actions[bot]"
    #       git config --global user.email "github-actions[bot]@users.noreply.github.com"
 
    #   - name: Deploy
    #     if: github.ref == 'refs/heads/main'
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}  
    #     run: npm run deploy
               